name: flutter_test_generator
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  http: ^1.2.2
  path: ^1.9.0
  interact: ^2.2.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
